#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IstaForm.Principal.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IstaAinAtiq")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertstagiaire(stagiaire instance);
    partial void Updatestagiaire(stagiaire instance);
    partial void Deletestagiaire(stagiaire instance);
    partial void Insertadministrateur(administrateur instance);
    partial void Updateadministrateur(administrateur instance);
    partial void Deleteadministrateur(administrateur instance);
    partial void Insertabsence(absence instance);
    partial void Updateabsence(absence instance);
    partial void Deleteabsence(absence instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::IstaForm.Properties.Settings.Default.IstaAinAtiqConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<stagiaire> stagiaire
		{
			get
			{
				return this.GetTable<stagiaire>();
			}
		}
		
		public System.Data.Linq.Table<administrateur> administrateur
		{
			get
			{
				return this.GetTable<administrateur>();
			}
		}
		
		public System.Data.Linq.Table<absence> absence
		{
			get
			{
				return this.GetTable<absence>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stagiaire")]
	public partial class stagiaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_inscriptionsessionprogramme;
		
		private string _MatriculeEtudiant;
		
		private string _Nom;
		
		private string _Prenom;
		
		private System.Nullable<char> _Sexe;
		
		private string _EtudiantActif;
		
		private string _diplome;
		
		private string _Principale;
		
		private string _LibelleLong;
		
		private string _CodeDiplome;
		
		private string _Code;
		
		private string _EtudiantPayant;
		
		private string _codediplome1;
		
		private string _prenom2;
		
		private string _DateNaissance;
		
		private string _Site;
		
		private string _Regimeinscription;
		
		private string _DateInscription;
		
		private string _DateDossierComplet;
		
		private string _LieuNaissance;
		
		private string _MotifAdmission;
		
		private string _CIN;
		
		private string _NTelelephone;
		
		private string _NTel_du_Tuteur;
		
		private string _Adresse;
		
		private string _Nationalite;
		
		private string _anneeEtude;
		
		private string _Nom_Arabe;
		
		private string _Prenom_arabe;
		
		private string _NiveauScolaire;
		
		private EntitySet<absence> _absence;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_inscriptionsessionprogrammeChanging(int value);
    partial void Onid_inscriptionsessionprogrammeChanged();
    partial void OnMatriculeEtudiantChanging(string value);
    partial void OnMatriculeEtudiantChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnSexeChanging(System.Nullable<char> value);
    partial void OnSexeChanged();
    partial void OnEtudiantActifChanging(string value);
    partial void OnEtudiantActifChanged();
    partial void OndiplomeChanging(string value);
    partial void OndiplomeChanged();
    partial void OnPrincipaleChanging(string value);
    partial void OnPrincipaleChanged();
    partial void OnLibelleLongChanging(string value);
    partial void OnLibelleLongChanged();
    partial void OnCodeDiplomeChanging(string value);
    partial void OnCodeDiplomeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnEtudiantPayantChanging(string value);
    partial void OnEtudiantPayantChanged();
    partial void Oncodediplome1Changing(string value);
    partial void Oncodediplome1Changed();
    partial void Onprenom2Changing(string value);
    partial void Onprenom2Changed();
    partial void OnDateNaissanceChanging(string value);
    partial void OnDateNaissanceChanged();
    partial void OnSiteChanging(string value);
    partial void OnSiteChanged();
    partial void OnRegimeinscriptionChanging(string value);
    partial void OnRegimeinscriptionChanged();
    partial void OnDateInscriptionChanging(string value);
    partial void OnDateInscriptionChanged();
    partial void OnDateDossierCompletChanging(string value);
    partial void OnDateDossierCompletChanged();
    partial void OnLieuNaissanceChanging(string value);
    partial void OnLieuNaissanceChanged();
    partial void OnMotifAdmissionChanging(string value);
    partial void OnMotifAdmissionChanged();
    partial void OnCINChanging(string value);
    partial void OnCINChanged();
    partial void OnNTelelephoneChanging(string value);
    partial void OnNTelelephoneChanged();
    partial void OnNTel_du_TuteurChanging(string value);
    partial void OnNTel_du_TuteurChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnNationaliteChanging(string value);
    partial void OnNationaliteChanged();
    partial void OnanneeEtudeChanging(string value);
    partial void OnanneeEtudeChanged();
    partial void OnNom_ArabeChanging(string value);
    partial void OnNom_ArabeChanged();
    partial void OnPrenom_arabeChanging(string value);
    partial void OnPrenom_arabeChanged();
    partial void OnNiveauScolaireChanging(string value);
    partial void OnNiveauScolaireChanged();
    #endregion
		
		public stagiaire()
		{
			this._absence = new EntitySet<absence>(new Action<absence>(this.attach_absence), new Action<absence>(this.detach_absence));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_inscriptionsessionprogramme", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_inscriptionsessionprogramme
		{
			get
			{
				return this._id_inscriptionsessionprogramme;
			}
			set
			{
				if ((this._id_inscriptionsessionprogramme != value))
				{
					this.Onid_inscriptionsessionprogrammeChanging(value);
					this.SendPropertyChanging();
					this._id_inscriptionsessionprogramme = value;
					this.SendPropertyChanged("id_inscriptionsessionprogramme");
					this.Onid_inscriptionsessionprogrammeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatriculeEtudiant", DbType="VarChar(25)")]
		public string MatriculeEtudiant
		{
			get
			{
				return this._MatriculeEtudiant;
			}
			set
			{
				if ((this._MatriculeEtudiant != value))
				{
					this.OnMatriculeEtudiantChanging(value);
					this.SendPropertyChanging();
					this._MatriculeEtudiant = value;
					this.SendPropertyChanged("MatriculeEtudiant");
					this.OnMatriculeEtudiantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="VarChar(40)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="Char(1)")]
		public System.Nullable<char> Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EtudiantActif", DbType="VarChar(3)")]
		public string EtudiantActif
		{
			get
			{
				return this._EtudiantActif;
			}
			set
			{
				if ((this._EtudiantActif != value))
				{
					this.OnEtudiantActifChanging(value);
					this.SendPropertyChanging();
					this._EtudiantActif = value;
					this.SendPropertyChanged("EtudiantActif");
					this.OnEtudiantActifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diplome", DbType="VarChar(60)")]
		public string diplome
		{
			get
			{
				return this._diplome;
			}
			set
			{
				if ((this._diplome != value))
				{
					this.OndiplomeChanging(value);
					this.SendPropertyChanging();
					this._diplome = value;
					this.SendPropertyChanged("diplome");
					this.OndiplomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Principale", DbType="VarChar(3)")]
		public string Principale
		{
			get
			{
				return this._Principale;
			}
			set
			{
				if ((this._Principale != value))
				{
					this.OnPrincipaleChanging(value);
					this.SendPropertyChanging();
					this._Principale = value;
					this.SendPropertyChanged("Principale");
					this.OnPrincipaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibelleLong", DbType="VarChar(90)")]
		public string LibelleLong
		{
			get
			{
				return this._LibelleLong;
			}
			set
			{
				if ((this._LibelleLong != value))
				{
					this.OnLibelleLongChanging(value);
					this.SendPropertyChanging();
					this._LibelleLong = value;
					this.SendPropertyChanged("LibelleLong");
					this.OnLibelleLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeDiplome", DbType="VarChar(25)")]
		public string CodeDiplome
		{
			get
			{
				return this._CodeDiplome;
			}
			set
			{
				if ((this._CodeDiplome != value))
				{
					this.OnCodeDiplomeChanging(value);
					this.SendPropertyChanging();
					this._CodeDiplome = value;
					this.SendPropertyChanged("CodeDiplome");
					this.OnCodeDiplomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EtudiantPayant", DbType="VarChar(3)")]
		public string EtudiantPayant
		{
			get
			{
				return this._EtudiantPayant;
			}
			set
			{
				if ((this._EtudiantPayant != value))
				{
					this.OnEtudiantPayantChanging(value);
					this.SendPropertyChanging();
					this._EtudiantPayant = value;
					this.SendPropertyChanged("EtudiantPayant");
					this.OnEtudiantPayantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codediplome1", DbType="VarChar(50)")]
		public string codediplome1
		{
			get
			{
				return this._codediplome1;
			}
			set
			{
				if ((this._codediplome1 != value))
				{
					this.Oncodediplome1Changing(value);
					this.SendPropertyChanging();
					this._codediplome1 = value;
					this.SendPropertyChanged("codediplome1");
					this.Oncodediplome1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom2", DbType="VarChar(50)")]
		public string prenom2
		{
			get
			{
				return this._prenom2;
			}
			set
			{
				if ((this._prenom2 != value))
				{
					this.Onprenom2Changing(value);
					this.SendPropertyChanging();
					this._prenom2 = value;
					this.SendPropertyChanged("prenom2");
					this.Onprenom2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateNaissance", DbType="VarChar(30)")]
		public string DateNaissance
		{
			get
			{
				return this._DateNaissance;
			}
			set
			{
				if ((this._DateNaissance != value))
				{
					this.OnDateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._DateNaissance = value;
					this.SendPropertyChanged("DateNaissance");
					this.OnDateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="VarChar(100)")]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this.OnSiteChanging(value);
					this.SendPropertyChanging();
					this._Site = value;
					this.SendPropertyChanged("Site");
					this.OnSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regimeinscription", DbType="VarChar(25)")]
		public string Regimeinscription
		{
			get
			{
				return this._Regimeinscription;
			}
			set
			{
				if ((this._Regimeinscription != value))
				{
					this.OnRegimeinscriptionChanging(value);
					this.SendPropertyChanging();
					this._Regimeinscription = value;
					this.SendPropertyChanged("Regimeinscription");
					this.OnRegimeinscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInscription", DbType="VarChar(30)")]
		public string DateInscription
		{
			get
			{
				return this._DateInscription;
			}
			set
			{
				if ((this._DateInscription != value))
				{
					this.OnDateInscriptionChanging(value);
					this.SendPropertyChanging();
					this._DateInscription = value;
					this.SendPropertyChanged("DateInscription");
					this.OnDateInscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDossierComplet", DbType="VarChar(30)")]
		public string DateDossierComplet
		{
			get
			{
				return this._DateDossierComplet;
			}
			set
			{
				if ((this._DateDossierComplet != value))
				{
					this.OnDateDossierCompletChanging(value);
					this.SendPropertyChanging();
					this._DateDossierComplet = value;
					this.SendPropertyChanged("DateDossierComplet");
					this.OnDateDossierCompletChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieuNaissance", DbType="VarChar(60)")]
		public string LieuNaissance
		{
			get
			{
				return this._LieuNaissance;
			}
			set
			{
				if ((this._LieuNaissance != value))
				{
					this.OnLieuNaissanceChanging(value);
					this.SendPropertyChanging();
					this._LieuNaissance = value;
					this.SendPropertyChanged("LieuNaissance");
					this.OnLieuNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotifAdmission", DbType="VarChar(60)")]
		public string MotifAdmission
		{
			get
			{
				return this._MotifAdmission;
			}
			set
			{
				if ((this._MotifAdmission != value))
				{
					this.OnMotifAdmissionChanging(value);
					this.SendPropertyChanging();
					this._MotifAdmission = value;
					this.SendPropertyChanged("MotifAdmission");
					this.OnMotifAdmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIN", DbType="VarChar(10)")]
		public string CIN
		{
			get
			{
				return this._CIN;
			}
			set
			{
				if ((this._CIN != value))
				{
					this.OnCINChanging(value);
					this.SendPropertyChanging();
					this._CIN = value;
					this.SendPropertyChanged("CIN");
					this.OnCINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NTelelephone", DbType="VarChar(14)")]
		public string NTelelephone
		{
			get
			{
				return this._NTelelephone;
			}
			set
			{
				if ((this._NTelelephone != value))
				{
					this.OnNTelelephoneChanging(value);
					this.SendPropertyChanging();
					this._NTelelephone = value;
					this.SendPropertyChanged("NTelelephone");
					this.OnNTelelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NTel_du_Tuteur", DbType="VarChar(14)")]
		public string NTel_du_Tuteur
		{
			get
			{
				return this._NTel_du_Tuteur;
			}
			set
			{
				if ((this._NTel_du_Tuteur != value))
				{
					this.OnNTel_du_TuteurChanging(value);
					this.SendPropertyChanging();
					this._NTel_du_Tuteur = value;
					this.SendPropertyChanged("NTel_du_Tuteur");
					this.OnNTel_du_TuteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="VarChar(100)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationalite", DbType="VarChar(15)")]
		public string Nationalite
		{
			get
			{
				return this._Nationalite;
			}
			set
			{
				if ((this._Nationalite != value))
				{
					this.OnNationaliteChanging(value);
					this.SendPropertyChanging();
					this._Nationalite = value;
					this.SendPropertyChanged("Nationalite");
					this.OnNationaliteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anneeEtude", DbType="VarChar(15)")]
		public string anneeEtude
		{
			get
			{
				return this._anneeEtude;
			}
			set
			{
				if ((this._anneeEtude != value))
				{
					this.OnanneeEtudeChanging(value);
					this.SendPropertyChanging();
					this._anneeEtude = value;
					this.SendPropertyChanged("anneeEtude");
					this.OnanneeEtudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Arabe", DbType="NVarChar(40)")]
		public string Nom_Arabe
		{
			get
			{
				return this._Nom_Arabe;
			}
			set
			{
				if ((this._Nom_Arabe != value))
				{
					this.OnNom_ArabeChanging(value);
					this.SendPropertyChanging();
					this._Nom_Arabe = value;
					this.SendPropertyChanged("Nom_Arabe");
					this.OnNom_ArabeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom_arabe", DbType="NVarChar(40)")]
		public string Prenom_arabe
		{
			get
			{
				return this._Prenom_arabe;
			}
			set
			{
				if ((this._Prenom_arabe != value))
				{
					this.OnPrenom_arabeChanging(value);
					this.SendPropertyChanging();
					this._Prenom_arabe = value;
					this.SendPropertyChanged("Prenom_arabe");
					this.OnPrenom_arabeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NiveauScolaire", DbType="VarChar(210)")]
		public string NiveauScolaire
		{
			get
			{
				return this._NiveauScolaire;
			}
			set
			{
				if ((this._NiveauScolaire != value))
				{
					this.OnNiveauScolaireChanging(value);
					this.SendPropertyChanging();
					this._NiveauScolaire = value;
					this.SendPropertyChanged("NiveauScolaire");
					this.OnNiveauScolaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="stagiaire_absence", Storage="_absence", ThisKey="id_inscriptionsessionprogramme", OtherKey="id_inscriptionsessionprogramme")]
		public EntitySet<absence> absence
		{
			get
			{
				return this._absence;
			}
			set
			{
				this._absence.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_absence(absence entity)
		{
			this.SendPropertyChanging();
			entity.stagiaire = this;
		}
		
		private void detach_absence(absence entity)
		{
			this.SendPropertyChanging();
			entity.stagiaire = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.administrateur")]
	public partial class administrateur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userA;
		
		private string _passwordA;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserAChanging(string value);
    partial void OnuserAChanged();
    partial void OnpasswordAChanging(string value);
    partial void OnpasswordAChanged();
    #endregion
		
		public administrateur()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userA", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userA
		{
			get
			{
				return this._userA;
			}
			set
			{
				if ((this._userA != value))
				{
					this.OnuserAChanging(value);
					this.SendPropertyChanging();
					this._userA = value;
					this.SendPropertyChanged("userA");
					this.OnuserAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwordA", DbType="VarChar(30)")]
		public string passwordA
		{
			get
			{
				return this._passwordA;
			}
			set
			{
				if ((this._passwordA != value))
				{
					this.OnpasswordAChanging(value);
					this.SendPropertyChanging();
					this._passwordA = value;
					this.SendPropertyChanged("passwordA");
					this.OnpasswordAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.absence")]
	public partial class absence : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodeAbsence;
		
		private System.Nullable<int> _id_inscriptionsessionprogramme;
		
		private System.Nullable<int> _joursAbsences;
		
		private string _justificaton;
		
		private System.Nullable<int> _jours_justifiés;
		
		private string _date_absence;
		
		private string _dateFinAbs;
		
		private EntityRef<stagiaire> _stagiaire;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeAbsenceChanging(int value);
    partial void OnCodeAbsenceChanged();
    partial void Onid_inscriptionsessionprogrammeChanging(System.Nullable<int> value);
    partial void Onid_inscriptionsessionprogrammeChanged();
    partial void OnjoursAbsencesChanging(System.Nullable<int> value);
    partial void OnjoursAbsencesChanged();
    partial void OnjustificatonChanging(string value);
    partial void OnjustificatonChanged();
    partial void Onjours_justifiésChanging(System.Nullable<int> value);
    partial void Onjours_justifiésChanged();
    partial void Ondate_absenceChanging(string value);
    partial void Ondate_absenceChanged();
    partial void OndateFinAbsChanging(string value);
    partial void OndateFinAbsChanged();
    #endregion
		
		public absence()
		{
			this._stagiaire = default(EntityRef<stagiaire>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeAbsence", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodeAbsence
		{
			get
			{
				return this._CodeAbsence;
			}
			set
			{
				if ((this._CodeAbsence != value))
				{
					this.OnCodeAbsenceChanging(value);
					this.SendPropertyChanging();
					this._CodeAbsence = value;
					this.SendPropertyChanged("CodeAbsence");
					this.OnCodeAbsenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_inscriptionsessionprogramme", DbType="Int")]
		public System.Nullable<int> id_inscriptionsessionprogramme
		{
			get
			{
				return this._id_inscriptionsessionprogramme;
			}
			set
			{
				if ((this._id_inscriptionsessionprogramme != value))
				{
					if (this._stagiaire.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_inscriptionsessionprogrammeChanging(value);
					this.SendPropertyChanging();
					this._id_inscriptionsessionprogramme = value;
					this.SendPropertyChanged("id_inscriptionsessionprogramme");
					this.Onid_inscriptionsessionprogrammeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joursAbsences", DbType="Int")]
		public System.Nullable<int> joursAbsences
		{
			get
			{
				return this._joursAbsences;
			}
			set
			{
				if ((this._joursAbsences != value))
				{
					this.OnjoursAbsencesChanging(value);
					this.SendPropertyChanging();
					this._joursAbsences = value;
					this.SendPropertyChanged("joursAbsences");
					this.OnjoursAbsencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_justificaton", DbType="VarChar(200)")]
		public string justificaton
		{
			get
			{
				return this._justificaton;
			}
			set
			{
				if ((this._justificaton != value))
				{
					this.OnjustificatonChanging(value);
					this.SendPropertyChanging();
					this._justificaton = value;
					this.SendPropertyChanged("justificaton");
					this.OnjustificatonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jours_justifiés", DbType="Int")]
		public System.Nullable<int> jours_justifiés
		{
			get
			{
				return this._jours_justifiés;
			}
			set
			{
				if ((this._jours_justifiés != value))
				{
					this.Onjours_justifiésChanging(value);
					this.SendPropertyChanging();
					this._jours_justifiés = value;
					this.SendPropertyChanged("jours_justifiés");
					this.Onjours_justifiésChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_absence", DbType="VarChar(25)")]
		public string date_absence
		{
			get
			{
				return this._date_absence;
			}
			set
			{
				if ((this._date_absence != value))
				{
					this.Ondate_absenceChanging(value);
					this.SendPropertyChanging();
					this._date_absence = value;
					this.SendPropertyChanged("date_absence");
					this.Ondate_absenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateFinAbs", DbType="VarChar(25)")]
		public string dateFinAbs
		{
			get
			{
				return this._dateFinAbs;
			}
			set
			{
				if ((this._dateFinAbs != value))
				{
					this.OndateFinAbsChanging(value);
					this.SendPropertyChanging();
					this._dateFinAbs = value;
					this.SendPropertyChanged("dateFinAbs");
					this.OndateFinAbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="stagiaire_absence", Storage="_stagiaire", ThisKey="id_inscriptionsessionprogramme", OtherKey="id_inscriptionsessionprogramme", IsForeignKey=true)]
		public stagiaire stagiaire
		{
			get
			{
				return this._stagiaire.Entity;
			}
			set
			{
				stagiaire previousValue = this._stagiaire.Entity;
				if (((previousValue != value) 
							|| (this._stagiaire.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._stagiaire.Entity = null;
						previousValue.absence.Remove(this);
					}
					this._stagiaire.Entity = value;
					if ((value != null))
					{
						value.absence.Add(this);
						this._id_inscriptionsessionprogramme = value.id_inscriptionsessionprogramme;
					}
					else
					{
						this._id_inscriptionsessionprogramme = default(Nullable<int>);
					}
					this.SendPropertyChanged("stagiaire");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
